import { useState } from "react";
import { Send, Copy, ExternalLink, ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "@/hooks/use-toast";
import { useNavigate } from "react-router-dom";

interface Message {
  id: string;
  type: "user" | "ai";
  content: string;
  citations?: string[];
}

const Chat = () => {
  const navigate = useNavigate();
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      type: "ai",
      content: "Hello! I'm PolicyPilot AI. I can help you with questions about company policies, procedures, and support documentation. What would you like to know?",
      citations: ["Company Policy Handbook v2.1", "Employee Guidelines"]
    }
  ]);
  const [inputValue, setInputValue] = useState("");

  const handleSendMessage = () => {
    if (!inputValue.trim()) return;

    const userMessage: Message = {
      id: Date.now().toString(),
      type: "user",
      content: inputValue,
    };

    setMessages(prev => [...prev, userMessage]);
    setInputValue("");

    // Simulate AI response
    setTimeout(() => {
      const aiMessage: Message = {
        id: (Date.now() + 1).toString(),
        type: "ai",
        content: `I understand you're asking about "${inputValue}". Based on our knowledge base, here's what I found... This is a demo response that would normally be generated by AI with relevant policy information.`,
        citations: ["Policy Document #123", "FAQ Section 4.2", "Support Guide v1.8"]
      };
      setMessages(prev => [...prev, aiMessage]);
    }, 1000);
  };

  const handleCopyMessage = (content: string) => {
    navigator.clipboard.writeText(content);
    toast({ title: "Message copied to clipboard" });
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  return (
    <div className="max-w-4xl mx-auto h-[calc(100vh-12rem)] flex flex-col">
      {/* Header */}
      <div className="mb-6">
        <div className="flex items-center gap-4 mb-4">
          <Button
            variant="outline"
            onClick={() => navigate('/chat/dashboard')}
            className="flex items-center gap-2 btn-glass"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Dashboard
          </Button>
        </div>
        <h1 className="text-3xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
          PolicyPilot – Chat
        </h1>
        <p className="text-muted-foreground mt-2">
          Ask questions about policies, procedures, and get AI-powered answers with citations.
        </p>
      </div>

      {/* Chat Container */}
      <div className="flex-1 glass-card p-6 flex flex-col">
        {/* Messages */}
        <div className="flex-1 overflow-y-auto space-y-4 mb-4 scrollbar-thin scrollbar-thumb-primary/20">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`flex ${message.type === "user" ? "justify-end" : "justify-start"}`}
            >
              <div className="max-w-[85%] space-y-2">
                <div
                  className={message.type === "user" ? "chat-user" : "chat-ai"}
                >
                  <p className="text-sm leading-relaxed">{message.content}</p>
                  {message.type === "ai" && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => handleCopyMessage(message.content)}
                      className="mt-2 h-6 px-2 text-xs hover:bg-white/10"
                    >
                      <Copy className="w-3 h-3 mr-1" />
                      Copy
                    </Button>
                  )}
                </div>

                {/* Citations */}
                {message.citations && (
                  <div className="flex flex-wrap gap-2 ml-2">
                    {message.citations.map((citation, index) => (
                      <button
                        key={index}
                        className="inline-flex items-center space-x-1 text-xs px-2 py-1 rounded-full bg-primary/10 text-primary hover:bg-primary/20 transition-colors glow-primary"
                      >
                        <ExternalLink className="w-3 h-3" />
                        <span>{citation}</span>
                      </button>
                    ))}
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* Input Area */}
        <div className="flex space-x-3">
          <Input
            placeholder="Ask a question..."
            value={inputValue}
            onChange={(e) => setInputValue(e.target.value)}
            onKeyPress={handleKeyPress}
            className="input-glass flex-1"
          />
          <Button
            onClick={handleSendMessage}
            disabled={!inputValue.trim()}
            className="btn-primary px-6"
          >
            <Send className="w-4 h-4" />
          </Button>
        </div>
      </div>
    </div>
  );
};

export default Chat;